module.exports = {
    w1: "Warriors",
    w2: "Mavericks",
    w3: "Trail Blazers",
    w4: "Lakers",
    w5: "Mavericks",
    w6: "Lakers",
    w7: "Mavericks",
    e1: "76ers",
    e2: "Knicks",
    e3: "Bucks",
    e4: "Nets",
    e5: "",
    e6: "",
    e7: "",
    champPick: "",
}